"""phase1 domain model

Revision ID: 373de370dc2d
Revises: 33fc46f9deae
Create Date: 2026-08-16 13:08:02.005600
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "373de370dc2d"
down_revision: str | None = "33fc46f9deae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_extractions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=60), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("prompt_version", sa.String(length=60), nullable=False),
        sa.Column("schema_version", sa.String(length=60), nullable=False),
        sa.Column(
            "structured_output",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "validation_state",
            sa.Enum("valid", "invalid", "fallback", name="ai_validation_state"),
            nullable=False,
        ),
        sa.Column(
            "provenance_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_extractions")),
    )
    op.create_index(
        op.f("ix_ai_extractions_input_hash"), "ai_extractions", ["input_hash"], unique=False
    )
    op.create_table(
        "households",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_households")),
    )
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "processing", "processed", "failed", "dead", name="outbox_status"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=1000), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_events")),
    )
    op.create_index(
        "ix_outbox_claimable", "outbox_events", ["status", "available_at"], unique=False
    )
    op.create_index(
        op.f("ix_outbox_events_aggregate_id"), "outbox_events", ["aggregate_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column(
            "account_state", sa.Enum("active", "disabled", name="account_state"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "memberships",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role", sa.Enum("owner", "admin", "member", name="membership_role"), nullable=False
        ),
        sa.Column(
            "notification_prefs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
            name=op.f("fk_memberships_household_id_households"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_memberships_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memberships")),
        sa.UniqueConstraint("user_id", "household_id", name="uq_memberships_user_household"),
    )
    op.create_index(
        op.f("ix_memberships_household_id"), "memberships", ["household_id"], unique=False
    )
    op.create_index(op.f("ix_memberships_user_id"), "memberships", ["user_id"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=True),
        sa.Column("actor_membership_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("resource_type", sa.String(length=80), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_membership_id"],
            ["memberships.id"],
            name=op.f("fk_audit_events_actor_membership_id_memberships"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
            name=op.f("fk_audit_events_household_id_households"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        op.f("ix_audit_events_created_at"), "audit_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_event_type"), "audit_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_household_id"), "audit_events", ["household_id"], unique=False
    )
    op.create_table(
        "responsibilities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("domain", sa.String(length=80), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "proposed",
                "active",
                "blocked",
                "transfer_pending",
                "completed",
                "archived",
                name="responsibility_status",
            ),
            nullable=False,
        ),
        sa.Column("current_owner_membership_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_membership_id", sa.Uuid(), nullable=False),
        sa.Column("completion_standard", sa.Text(), nullable=True),
        sa.Column("scope_version", sa.Integer(), nullable=False),
        sa.Column("ownership_version", sa.Integer(), nullable=False),
        sa.Column("optimistic_version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status = 'draft' OR current_owner_membership_id IS NOT NULL",
            name=op.f("ck_responsibilities_non_draft_has_owner"),
        ),
        sa.CheckConstraint(
            "ownership_version >= 1", name=op.f("ck_responsibilities_ownership_version_positive")
        ),
        sa.CheckConstraint(
            "scope_version >= 1", name=op.f("ck_responsibilities_scope_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_membership_id"],
            ["memberships.id"],
            name=op.f("fk_responsibilities_created_by_membership_id_memberships"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["current_owner_membership_id"],
            ["memberships.id"],
            name=op.f("fk_responsibilities_current_owner_membership_id_memberships"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
            name=op.f("fk_responsibilities_household_id_households"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_responsibilities")),
    )
    op.create_index(
        op.f("ix_responsibilities_current_owner_membership_id"),
        "responsibilities",
        ["current_owner_membership_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_responsibilities_household_id"), "responsibilities", ["household_id"], unique=False
    )
    op.create_index(
        op.f("ix_responsibilities_status"), "responsibilities", ["status"], unique=False
    )
    op.create_table(
        "ownership_contracts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("responsibility_id", sa.Uuid(), nullable=False),
        sa.Column("proposer_membership_id", sa.Uuid(), nullable=False),
        sa.Column("source_owner_membership_id", sa.Uuid(), nullable=True),
        sa.Column("proposed_owner_membership_id", sa.Uuid(), nullable=False),
        sa.Column("expected_scope_version", sa.Integer(), nullable=False),
        sa.Column("expected_ownership_version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "accepted",
                "declined",
                "canceled",
                "expired",
                "stale",
                name="contract_status",
            ),
            nullable=False,
        ),
        sa.Column("completion_standard_snapshot", sa.Text(), nullable=True),
        sa.Column(
            "lifecycle_scope_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "recurrence_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "backup_policy",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "proposed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("declined_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["proposed_owner_membership_id"],
            ["memberships.id"],
            name=op.f("fk_ownership_contracts_proposed_owner_membership_id_memberships"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposer_membership_id"],
            ["memberships.id"],
            name=op.f("fk_ownership_contracts_proposer_membership_id_memberships"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["responsibility_id"],
            ["responsibilities.id"],
            name=op.f("fk_ownership_contracts_responsibility_id_responsibilities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_owner_membership_id"],
            ["memberships.id"],
            name=op.f("fk_ownership_contracts_source_owner_membership_id_memberships"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ownership_contracts")),
    )
    op.create_index(
        op.f("ix_ownership_contracts_proposed_owner_membership_id"),
        "ownership_contracts",
        ["proposed_owner_membership_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ownership_contracts_responsibility_id"),
        "ownership_contracts",
        ["responsibility_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ownership_contracts_status"), "ownership_contracts", ["status"], unique=False
    )
    op.create_table(
        "recurrence_rules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("responsibility_id", sa.Uuid(), nullable=False),
        sa.Column("rrule", sa.Text(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("anchor_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("next_materialization_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["responsibility_id"],
            ["responsibilities.id"],
            name=op.f("fk_recurrence_rules_responsibility_id_responsibilities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recurrence_rules")),
    )
    op.create_index(
        op.f("ix_recurrence_rules_next_materialization_at"),
        "recurrence_rules",
        ["next_materialization_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recurrence_rules_responsibility_id"),
        "recurrence_rules",
        ["responsibility_id"],
        unique=True,
    )
    op.create_table(
        "responsibility_cycles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("responsibility_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "active", "completed", "skipped", name="cycle_status"),
            nullable=False,
        ),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("target_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "sequence >= 1", name=op.f("ck_responsibility_cycles_sequence_positive")
        ),
        sa.ForeignKeyConstraint(
            ["responsibility_id"],
            ["responsibilities.id"],
            name=op.f("fk_responsibility_cycles_responsibility_id_responsibilities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_responsibility_cycles")),
        sa.UniqueConstraint(
            "responsibility_id", "sequence", name="uq_cycles_responsibility_sequence"
        ),
    )
    op.create_index(
        op.f("ix_responsibility_cycles_responsibility_id"),
        "responsibility_cycles",
        ["responsibility_id"],
        unique=False,
    )
    op.create_table(
        "lifecycle_steps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("cycle_id", sa.Uuid(), nullable=False),
        sa.Column("step_key", sa.String(length=80), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "anticipate",
                "options",
                "decide",
                "prepare",
                "execute",
                "verify",
                "follow_up",
                "recur",
                name="lifecycle_kind",
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("ordering", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "in_progress", "done", "blocked", "skipped", name="step_status"),
            nullable=False,
        ),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "provenance",
            sa.Enum("user_explicit", "ai_inferred", "deterministic", name="provenance"),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("is_assumption", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name=op.f("ck_lifecycle_steps_confidence_unit_interval"),
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["responsibility_cycles.id"],
            name=op.f("fk_lifecycle_steps_cycle_id_responsibility_cycles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lifecycle_steps")),
        sa.UniqueConstraint("cycle_id", "step_key", name="uq_steps_cycle_key"),
    )
    op.create_index(
        op.f("ix_lifecycle_steps_cycle_id"), "lifecycle_steps", ["cycle_id"], unique=False
    )
    op.create_table(
        "ownership_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("responsibility_id", sa.Uuid(), nullable=False),
        sa.Column("contract_id", sa.Uuid(), nullable=True),
        sa.Column(
            "event_type",
            sa.Enum(
                "created",
                "proposed",
                "accepted",
                "declined",
                "canceled",
                "transferred",
                "escalated",
                "completed",
                "archived",
                name="ownership_event_type",
            ),
            nullable=False,
        ),
        sa.Column("actor_membership_id", sa.Uuid(), nullable=True),
        sa.Column("previous_owner_membership_id", sa.Uuid(), nullable=True),
        sa.Column("new_owner_membership_id", sa.Uuid(), nullable=True),
        sa.Column("ownership_version", sa.Integer(), nullable=False),
        sa.Column(
            "reason_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_membership_id"],
            ["memberships.id"],
            name=op.f("fk_ownership_events_actor_membership_id_memberships"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["ownership_contracts.id"],
            name=op.f("fk_ownership_events_contract_id_ownership_contracts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["new_owner_membership_id"],
            ["memberships.id"],
            name=op.f("fk_ownership_events_new_owner_membership_id_memberships"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["previous_owner_membership_id"],
            ["memberships.id"],
            name=op.f("fk_ownership_events_previous_owner_membership_id_memberships"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["responsibility_id"],
            ["responsibilities.id"],
            name=op.f("fk_ownership_events_responsibility_id_responsibilities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ownership_events")),
    )
    op.create_index(
        op.f("ix_ownership_events_created_at"), "ownership_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_ownership_events_responsibility_id"),
        "ownership_events",
        ["responsibility_id"],
        unique=False,
    )
    op.create_table(
        "reminders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("responsibility_id", sa.Uuid(), nullable=False),
        sa.Column("cycle_id", sa.Uuid(), nullable=False),
        sa.Column("lifecycle_step_id", sa.Uuid(), nullable=True),
        sa.Column("recipient_membership_id", sa.Uuid(), nullable=False),
        sa.Column("ownership_version", sa.Integer(), nullable=False),
        sa.Column(
            "reminder_type",
            sa.Enum("step_due", "cycle_due", "overdue", "escalation", name="reminder_type"),
            nullable=False,
        ),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "state",
            sa.Enum("scheduled", "canceled", "fired", "superseded", name="reminder_state"),
            nullable=False,
        ),
        sa.Column("dedupe_key", sa.String(length=255), nullable=False),
        sa.Column("fired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["responsibility_cycles.id"],
            name=op.f("fk_reminders_cycle_id_responsibility_cycles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["lifecycle_step_id"],
            ["lifecycle_steps.id"],
            name=op.f("fk_reminders_lifecycle_step_id_lifecycle_steps"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recipient_membership_id"],
            ["memberships.id"],
            name=op.f("fk_reminders_recipient_membership_id_memberships"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["responsibility_id"],
            ["responsibilities.id"],
            name=op.f("fk_reminders_responsibility_id_responsibilities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reminders")),
    )
    op.create_index("ix_reminders_due", "reminders", ["state", "scheduled_for"], unique=False)
    op.create_index(
        "ix_reminders_recipient", "reminders", ["recipient_membership_id"], unique=False
    )
    op.create_index(
        op.f("ix_reminders_responsibility_id"), "reminders", ["responsibility_id"], unique=False
    )
    op.create_index("uq_reminders_dedupe", "reminders", ["dedupe_key"], unique=True)
    op.create_table(
        "step_dependencies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("cycle_id", sa.Uuid(), nullable=False),
        sa.Column("from_step_id", sa.Uuid(), nullable=False),
        sa.Column("to_step_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "from_step_id <> to_step_id", name=op.f("ck_step_dependencies_no_self_dependency")
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["responsibility_cycles.id"],
            name=op.f("fk_step_dependencies_cycle_id_responsibility_cycles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["from_step_id"],
            ["lifecycle_steps.id"],
            name=op.f("fk_step_dependencies_from_step_id_lifecycle_steps"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_step_id"],
            ["lifecycle_steps.id"],
            name=op.f("fk_step_dependencies_to_step_id_lifecycle_steps"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_step_dependencies")),
        sa.UniqueConstraint("from_step_id", "to_step_id", name="uq_step_dep_edge"),
    )
    op.create_index(
        op.f("ix_step_dependencies_cycle_id"), "step_dependencies", ["cycle_id"], unique=False
    )
    op.create_table(
        "notification_deliveries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("reminder_id", sa.Uuid(), nullable=True),
        sa.Column("channel", sa.Enum("in_app", "email", name="delivery_channel"), nullable=False),
        sa.Column("recipient_membership_id", sa.Uuid(), nullable=False),
        sa.Column("provider_message_id", sa.String(length=255), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "processing",
                "provider_accepted",
                "delivered",
                "retryable_failure",
                "permanent_failure",
                "canceled",
                name="delivery_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_type", sa.String(length=80), nullable=True),
        sa.Column("provider_response", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["recipient_membership_id"],
            ["memberships.id"],
            name=op.f("fk_notification_deliveries_recipient_membership_id_memberships"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reminder_id"],
            ["reminders.id"],
            name=op.f("fk_notification_deliveries_reminder_id_reminders"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_deliveries")),
    )
    op.create_index(
        op.f("ix_notification_deliveries_reminder_id"),
        "notification_deliveries",
        ["reminder_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_notification_deliveries_reminder_id"), table_name="notification_deliveries"
    )
    op.drop_table("notification_deliveries")
    op.drop_index(op.f("ix_step_dependencies_cycle_id"), table_name="step_dependencies")
    op.drop_table("step_dependencies")
    op.drop_index("uq_reminders_dedupe", table_name="reminders")
    op.drop_index(op.f("ix_reminders_responsibility_id"), table_name="reminders")
    op.drop_index("ix_reminders_recipient", table_name="reminders")
    op.drop_index("ix_reminders_due", table_name="reminders")
    op.drop_table("reminders")
    op.drop_index(op.f("ix_ownership_events_responsibility_id"), table_name="ownership_events")
    op.drop_index(op.f("ix_ownership_events_created_at"), table_name="ownership_events")
    op.drop_table("ownership_events")
    op.drop_index(op.f("ix_lifecycle_steps_cycle_id"), table_name="lifecycle_steps")
    op.drop_table("lifecycle_steps")
    op.drop_index(
        op.f("ix_responsibility_cycles_responsibility_id"), table_name="responsibility_cycles"
    )
    op.drop_table("responsibility_cycles")
    op.drop_index(op.f("ix_recurrence_rules_responsibility_id"), table_name="recurrence_rules")
    op.drop_index(
        op.f("ix_recurrence_rules_next_materialization_at"), table_name="recurrence_rules"
    )
    op.drop_table("recurrence_rules")
    op.drop_index(op.f("ix_ownership_contracts_status"), table_name="ownership_contracts")
    op.drop_index(
        op.f("ix_ownership_contracts_responsibility_id"), table_name="ownership_contracts"
    )
    op.drop_index(
        op.f("ix_ownership_contracts_proposed_owner_membership_id"),
        table_name="ownership_contracts",
    )
    op.drop_table("ownership_contracts")
    op.drop_index(op.f("ix_responsibilities_status"), table_name="responsibilities")
    op.drop_index(op.f("ix_responsibilities_household_id"), table_name="responsibilities")
    op.drop_index(
        op.f("ix_responsibilities_current_owner_membership_id"), table_name="responsibilities"
    )
    op.drop_table("responsibilities")
    op.drop_index(op.f("ix_audit_events_household_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_event_type"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_created_at"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_memberships_user_id"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_household_id"), table_name="memberships")
    op.drop_table("memberships")
    op.drop_table("users")
    op.drop_index(op.f("ix_outbox_events_aggregate_id"), table_name="outbox_events")
    op.drop_index("ix_outbox_claimable", table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_table("households")
    op.drop_index(op.f("ix_ai_extractions_input_hash"), table_name="ai_extractions")
    op.drop_table("ai_extractions")
    # ### end Alembic commands ###
