"""phase7 8 in_app_notifications

Revision ID: 42b62f189167
Revises: 9c2747bbade9
Create Date: 2026-08-16 16:32:05.675136
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "42b62f189167"
down_revision: str | None = "9c2747bbade9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "in_app_notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("recipient_membership_id", sa.Uuid(), nullable=False),
        sa.Column("responsibility_id", sa.Uuid(), nullable=True),
        sa.Column("reminder_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("deep_link", sa.String(length=500), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["recipient_membership_id"],
            ["memberships.id"],
            name=op.f("fk_in_app_notifications_recipient_membership_id_memberships"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reminder_id"],
            ["reminders.id"],
            name=op.f("fk_in_app_notifications_reminder_id_reminders"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["responsibility_id"],
            ["responsibilities.id"],
            name=op.f("fk_in_app_notifications_responsibility_id_responsibilities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_in_app_notifications")),
    )
    op.create_index(
        op.f("ix_in_app_notifications_recipient_membership_id"),
        "in_app_notifications",
        ["recipient_membership_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_in_app_notifications_recipient_membership_id"), table_name="in_app_notifications"
    )
    op.drop_table("in_app_notifications")
    # ### end Alembic commands ###
